name:                dot-reverse
version:             0.1.0.0
#synopsis:
#description:

dependencies:
  - base >= 4.7 && < 5
  - containers
  - doctest
  - dot-graph
  - graph-wrapper
  - language-dot

executables:
  dot-reverse:
    source-dirs:      src
    main:             Main.hs
    ghc-options:      -W -Wall
